[build-system]
requires = ["setuptools","numpy==1.26.4", "pyarrow===14.0.1","pybind11","pip"]
build-backend = "setuptools.build_meta"

[project]
name = "lingodb-bridge"
version = "0.0.1"
dependencies = [
    "numpy===1.26.4",
    "pyarrow===14.0.1"
]