name: Clang Tidy Check
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ghcr.io/lingo-db/lingodb-dev:c26a3fc2f7789da61d04b7e416915a530b70db2d 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          make clean
          make lint